create table student (
	stu_id SERIAL NOT NULL PRIMARY KEY,
	stu_name VARCHAR(50) NOT NULL,
	gpa INT NOT NULL,
	stu_img_url TEXT NOT NULL,
	campus VARCHAR(50) ,
	email VARCHAR(250) NOT NULL
);
insert into student (stu_id, stu_name, gpa, stu_img_url, campus, email) values (1, 'Garvin Aireton', 1, 'https://images.generated.photos/ywPCC-wnQ9k4yFPh9Bm0regReQmnm0k4sJmx8VB2c5A/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/NTQ4NTgzLmpwZw.jpg', 'Baruch College', 'gaireton0@miibeian.gov.cn');
insert into student (stu_id, stu_name, gpa, stu_img_url, campus, email) values (2, 'Ollie Abeau', 3, 'https://images.generated.photos/rF4wxnkJB05QCyY5eH_0IJKZocKAVGPVNwXCC_a0Vuw/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/ODc1MjU2LmpwZw.jpg', 'Brooklyn College', 'oabeau1@shareasale.com');
insert into student (stu_id, stu_name, gpa, stu_img_url, campus, email) values (3, 'Oliy Rappa', 1, 'https://images.generated.photos/IiEuf1b4H3hSgwYVbBb5gC5oYXFnChpVTebEI2ZMKE4/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MjcwMDI0LmpwZw.jpg', null, 'orappa2@bizjournals.com');
insert into student (stu_id, stu_name, gpa, stu_img_url, campus, email) values (4, 'Blithe Elcomb', 4, 'https://images.generated.photos/2xsAky_fbIK_KfAnpCQx4hbhpx4h6j1ZJFmbJMiGcWA/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MDA1NzA2LmpwZw.jpg', 'Baruch College', 'belcomb3@digg.com');
insert into student (stu_id, stu_name, gpa, stu_img_url, campus, email) values (5, 'Egbert Dumbelton', 2, 'https://images.generated.photos/c1K0keuKcT9_k-PcN2Rv0RWHEL7vbY1YVcWnIILfRA0/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/Mjk5NDA1LmpwZw.jpg', 'Hunter College', 'edumbelton4@pinterest.com');
insert into student (stu_id, stu_name, gpa, stu_img_url, campus, email) values (6, 'Nicolais Callingham', 3, 'https://images.generated.photos/MnMiiGGAKidu4MUWu15UmMuOMOZGXC4NpFf2h9WyJD8/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/NTE3NTUyLmpwZw.jpg', null, 'ncallingham5@opensource.org');
insert into student (stu_id, stu_name, gpa, stu_img_url, campus, email) values (7, 'Rudyard Hurlston', 2, 'https://images.generated.photos/QEgtGPPK1dAMsfkWCunC5Y-tUp7wUpSPWSSuymxjdcY/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MzgzOTY2LmpwZw.jpg', 'Brooklyn College', 'rhurlston6@google.pl');
insert into student (stu_id, stu_name, gpa, stu_img_url, campus, email) values (8, 'Casper Roughan', 3, 'https://images.generated.photos/Uqs8KsUYSt-zKNl73q7-LU7Z4w3oYuIQyEMbmfunErg/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/NTU2MDQ3LmpwZw.jpg', 'City College of New York', 'croughan7@japanpost.jp');
insert into student (stu_id, stu_name, gpa, stu_img_url, campus, email) values (9, 'Leah Blachford', 2, 'https://images.generated.photos/DQCgfY4VzqCQiXzKfqgkWWLudHnVIEIQk6PzMV1KQSo/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MjU2ODc4LmpwZw.jpg', 'Hunter College', 'lblachford8@icq.com');
insert into student (stu_id, stu_name, gpa, stu_img_url, campus, email) values (10, 'Sasha Cancutt', 3, 'https://images.generated.photos/2t_fqzmh637EfM62gF70JRDDs1UZ9PU3VNHsEJil1zM/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/NzI3ODM3LmpwZw.jpg', 'City College of New York', 'scancutt9@unesco.org');


create table campuses (
	campus_id SERIAL NOT NULL PRIMARY KEY,
	campus_name VARCHAR(50) NOT NULL,
	campus_location VARCHAR(250) NOT NULL,
	campus_img_url TEXT NOT NULL,
	campus_description TEXT
);
insert into campuses (campus_id, campus_name, campus_location, campus_img_url, campus_description) values (1, 'City College of New York', '160 Convent Ave, New York, NY 10031', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/City_College_of_New_York_-_High_School_for_Math%2C_Science_and_Engineering_at_City_College_%2848170427012%29.jpg/800px-City_College_of_New_York_-_High_School_for_Math%2C_Science_and_Engineering_at_City_College_%2848170427012%29.jpg', 'The City College of the City University of New York is a public college of the City University of New York system in New York City. Founded in 1847, City College was the first free public institution of higher education in the United States.');
insert into campuses (campus_id, campus_name, campus_location, campus_img_url, campus_description) values (2, 'Baruch College', '55 Lexington Ave, New York, NY 10010', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyYlLBMHWbEHHDSaiqeSmT--kSzvkW-5WaqQ&usqp=CAU', 'Baruch College (officially the Bernard M. Baruch College) is a public college in New York City. It is a constituent college of the City University of New York system. Named for financier and statesman Bernard M. Baruch, the college operates undergraduate and postgraduate programs through the Zicklin School of Business, the Weissman School of Arts and Sciences, and the Marxe School of Public and International Affairs.');
insert into campuses (campus_id, campus_name, campus_location, campus_img_url, campus_description) values (3, 'Brooklyn College', '2900 Bedford Ave, Brooklyn, NY 11210', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm4wWfnPQYFhCZSaixLTasFgibie-JqXqe3Q&usqp=CAU', 'Brooklyn College is a public university in Brooklyn, New York. It is part of the City University of New York system and enrolls about 15,000 undergraduate and 2,800 graduate students on a 35-acre campus.');
insert into campuses (campus_id, campus_name, campus_location, campus_img_url, campus_description) values (4, 'Hunter College', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgdQKFF2FF4Tzlmtbv9HTWVwipnfQMwAPe6g&usqp=CAU', 'https://robohash.org/omnisexvoluptate.png?size=50x50&set=set1', 'Hunter College is one of the constituent colleges of the City University of New York, a public university in New York City. The college offers studies in more than one hundred undergraduate and postgraduate fields across five schools. It also administers Hunter College High School and Hunter College Elementary School. ');
insert into campuses (campus_id, campus_name, campus_location, campus_img_url, campus_description) values (5, 'John Jay College of Criminal Justice', '524 W 59th St, New York, NY 10019', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbDuJIj4OPqVsb2dP8byVx8Xb-JRfvetZ2CQ&usqp=CAU', 'The John Jay College of Criminal Justice is a public college focused on criminal justice and located in New York City. It is a senior college of the City University of New York. John Jay was founded as the only liberal arts college with a criminal justice and forensic focus in the United States.');	

